### ISSUE TITLE
Display defines when there are differences in configuration in the project

### ISSUE THREAD

**Issue by de-sach** [pluyckx/iar-vsc#42]
Some IAR projects have different configurations (e.g. defines, optimizations, ...) for different files or folders.
It would be nice if the extension could parse all defines in all these levels and show the correct options for the correct files.

**Comment by pluyckx** [comment]
One of the goals is to also edit the *ewp* file from VSCode. When I figured out how I am going to implement that, I can fix this.

**Comment by HampusAdolfsson** [comment]
This is implemented in 1.3.0 (per-file defines that is, not editing ewp files).
