### ISSUE TITLE
Remove IAR project related configuration from vscode settings file

### ISSUE THREAD

**Issue by pluyckx** [pluyckx/iar-vsc#51]
**Is your feature request related to a problem? Please describe.**
When adding the `settings.json` file to a `version control system` like _git_, this creates unwanted changes because the installation paths for the `workbench` and `compiler` can be different between users. Also the selected `project` and/or selected `configuration` can be different.

**Describe the solution you'd like**
Move those settings to a separate file so it is possible to share the `settings.json` file from vscode, but keep the IAR configuration settings file (`iar-vsc.json`) local.

**Describe alternatives you've considered**
Using the global section of the vscode settings. However, this causes problems when working on different projects at the same time.

**Comment by HampusAdolfsson** [comment]
Implemented in 1.2.0
