### ISSUE TITLE
compilerPath in c_cpp_properties.json not set

### ISSUE THREAD

**Issue by ben-edna** [pluyckx/iar-vsc#54]
**Describe the bug**
When choosing the IAR configuration for intellisense the `compilerPath` field is not (explicitly) set and deduced by VSCode. In my case gcc is installed on the system and VSCode queries it for defines resulting in `__GNUCC__` being defined and some unrelated include errors to be shown.

**To Reproduce**
1. Have system with GCC installed
2. Use IAR config per documentation of plugin
3. GCC is queried for defines (and include paths)

**Expected behavior**
GCC (or any other compiler) should not be queried

**Screenshots**
Faulty behavior:
![afbeelding](https://user-images.githubusercontent.com/37540691/58800845-43183b80-8609-11e9-8ce7-ee8ef953e64f.png)

After adding `compilerPath:""` to  IAR config in `c_cpp_properties.json`:
![afbeelding](https://user-images.githubusercontent.com/37540691/58800916-6a6f0880-8609-11e9-88dc-4e5a6955ceb5.png)

**Additional context**
Read more about `compilerPath` [here](https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/c_cpp_properties.json.md#compilerpath-optional)

**Comment by ben-edna** [comment]
Maybe related to #53

**Comment by HampusAdolfsson** [comment]
Implemented in 1.2.0
