### ISSUE TITLE
includePath incorrectly populated for TOOLKIT_DIR

### ISSUE THREAD

**Issue by pouyaman** [pluyckx/iar-vsc#57]
**Describe the bug**
When generating c_cpp_properties.json file, the includePath is not correctly populated for $TOOLKIT_DIR$ entries.

**To Reproduce**
1. Setup project, iar etc...
2. Generate CppTools config file

**EWP Content**

>                     <state>$TOOLKIT_DIR$\inc\c</state>
>                     <state>$TOOLKIT_DIR$\inc\Microchip\saml21</state>
>                     <state>$TOOLKIT_DIR$\CMSIS\Core\Include</state>
>                     <state>$PROJ_DIR$\asf\</state>

**Expected Output**

>                 "C:\\Program Files (x86)\\IAR Systems\\Embedded Workbench 8.2\\arm\\inc\\Microchip\\saml21",
>                 "C:\\Program Files (x86)\\IAR Systems\\Embedded Workbench 8.2\\arm\\CMSIS\\Core\\Include",
>                 "C:\\Program Files (x86)\\IAR Systems\\Embedded Workbench 8.2\\arm\\inc\\c",
>                 "SW\\Embedded\\asf"

**Actual Output**

>                 "C:\\Users\\pouya\\AppData\\Local\\Programs\\Microsoft VS Code\\$TOOLKIT_DIR$\\inc\\c",
>                 "C:\\Users\\pouya\\AppData\\Local\\Programs\\Microsoft VS Code\\$TOOLKIT_DIR$\\inc\\Microchip\\saml21",
>                 "C:\\Users\\pouya\\AppData\\Local\\Programs\\Microsoft VS Code\\$TOOLKIT_DIR$\\CMSIS\\Core\\Include",
>                 "SW\\Embedded\\asf",
>                 "C:\\Program Files (x86)\\IAR Systems\\Embedded Workbench 8.2\\arm\\inc",
>                 "C:\\Program Files (x86)\\IAR Systems\\Embedded Workbench 8.2\\arm\\inc\\c"

**Comment by sm-github-work** [comment]
I also have this issue using the latest iar-vsc release 1.2.1.  My EWARM version is 8.50.1.  I have the issue with the CMSIS include ($TOOLKIT_DIR$\CMSIS\Core\Include).  It is generated as: 
"..\\..\\Users\\Dev\\AppData\\Local\\Programs\\Microsoft VS Code\\$TOOLKIT_DIR$\\CMSIS\\Core\\Include",
Oddly enough, I don't include the std c directory in my project, but it seems to get appended automatically and correctly as: 
"C:\\Program Files (x86)\\IAR Systems\\Embedded Workbench 8.4\\arm\\inc\\c"

I am unable to correct with a manual workaround, as the c_cpp_properties file is automatically generated.
It looks like there is an issue to work on this, but I thought another data point couldn't hurt.

**Comment by HampusAdolfsson** [comment]
This should now work correctly in the latest release (1.3.0). Please let me know otherwise.
