### ISSUE TITLE
How to Use VS Code + IAR Simulator

### ISSUE THREAD

**Issue by thomasfinchbr** [pluyckx/iar-vsc#72]
Hi,

I have a bunch of unit test that I run on IAR simulator for ARM.
I would like to know if it is possible to connect to the IAR simulator using a GDB server?
I would like to debug these unit tests using VS Code environment.

Thanks.

**Comment by ben-edna** [comment]
IAR C-spy debugger has no GDB frontend as far as I could figure out, but I do run my (CppUTest based) unit-tests from VSCode (although no debugging 😞).

I've created a task in `tasks.json` that does a build (`"dependsOn": "Iar Build"`) and runs the `iarvsc.outFile` in the simulator using `cspybat.exe`. The arguments needed can be taken from the `.cspy.bat` and `.xcl` files in the settings folder where your `.ewp` is.
It would be great if this plugin would generate or parse the `.cspy.bat` and `.xcl` files from the settings folder itself.

The `iarvsc.outFile` is (currently) not parsed from the `.ewp` see #36 and you should add this manually to your settings.

The `problemMatcher` is CppUTest specific, but can be adapted for any other framework. 

```json
"tasks": [
        {
            "type": "process",
            "command": "${config:iarvsc.workbench}\\common\\bin\\cspybat.exe",
            "args": [
                   "${config:iarvsc.workbench}\\arm\\bin\\armproc.dll",
                   "${config:iarvsc.workbench}\\arm\\bin\\armsim2.dll", 
                   "${config:iarvsc.outFile}",
                   "--plugin", "${config:iarvsc.workbench}\\arm\\bin\\armbat.dll",
                   "--backend", "--endian=little", "--cpu=Cortex-M3",
                   "--fpu=None", "--semihosting", "--multicore_nr_of_cores=1",
            ],
            "label": "Unittest",
            "group": {
                "kind": "test",
                "isDefault": true
            },
            "dependsOn": "Iar Build", 
            "problemMatcher": {
                "owner": "iar",
                "fileLocation": "absolute",
                "pattern": [
                    {
                        "regexp": "^([^\\\\]*[^:]+):(\\d+):\\s*(.*):.*$",
                        "file": 1,
                        "line": 2,
                        "severity": 3,
                    },
                    {
                        "regexp": "^(\\s+.+)$",
                        "message": 1,
                    } 
                ]
            }
        }
```

**Comment by thomasfinchbr** [comment]
Thanks for your answer. 
I was able to run my unit test form inside VS code.
