### ISSUE TITLE
Load external compiler defines to 

### ISSUE THREAD

**Issue by idk84** [pluyckx/iar-vsc#81]
name | about | title | labels | assignees
------ | ------ | ----- | ------ | -----------
Update c_cpp_properties.json from external file | IAR allows for setting compiler defines from an external file, specified in the Extra Options using the -f MyConfigFile.xcl option.  If such an external file is specified, parse it for compiler defines and update c_cpp_properties.json |   |   |  

I have several compiler defines specified in external files.  When I load the project, VSC does not recognize those compiler defines because they are not updated in c_cpp_properties.json.

This iar-vsc extension could check the project ewp file for extra options.  If an external compiler config file(s) is specified, parse that file for compiler defines and update c_cpp_properties.json.

![ExtraOptions](https://user-images.githubusercontent.com/65189624/81600666-ff40c100-9397-11ea-9e2d-4ca6ddf0c2ef.PNG)

**Comment by SunmyMao** [comment]
vote

**Comment by HampusAdolfsson** [comment]
Hi, and sorry for the late reply.

We just released an overhaul to the include path and define system that fixes a bunch of related bugs.
It should also fix this one, please let me know if it doesn't.

**Comment by idk84** [comment]
Great, thanks. I will try it out.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
