### ISSUE TITLE
Is it possible to debug through Silicon Labs 2 wire C2 interface?

### ISSUE THREAD

**Issue by jscabrera81** [pluyckx/iar-vsc#84]
Could I connect an  in-circuit  debugger like "C2 interface" debug adapter by Silabs?

Thanks in advance for your answer.

**Comment by HampusAdolfsson** [comment]
Unfortunately, it's not possible right now to do this with Silabs' own Debug adapter ([this one](https://www.silabs.com/products/development-tools/mcu/8-bit/8bit-mcu-accessories/8-bit-debug-adapter)).

However, VS Code can connect to a J-link adapter (using a GDB server), and Segger provide a [JTAG to C2](https://www.segger.com/products/debug-probes/j-link/accessories/adapters/silabs-c2-adapter/) adapter that can be used to debug over the C2 interface with a J-link. This way it would work.

There is some documentation about debugging using a J-link in the readme:
https://github.com/pluyckx/iar-vsc/tree/master/Extension#Debugging
And also some documentation about J-link's GDB server here:
https://www.segger.com/products/debug-probes/j-link/tools/j-link-gdb-server/about-j-link-gdb-server/

**Comment by jscabrera81** [comment]
Really appreciate  for your answer. I'll take your recommendation into account.
