### ISSUE TITLE
Use tasks to call the IAR compiler instead of using a build command inside the extension

### ISSUE THREAD

**Issue by pluyckx** [pluyckx/iar-vsc#9]
Now the extension itself calls the iar compiler (builder). Because of this, compiler errors and warnings do not occur in the _Problems_ tab. When using a build task, a regexp can be used to parse the compiler output and add the errors/warnings to the _Problems_ tab.

Create a **Create Build Tasks** command which creates a build task for each configuration found in the ewp.

**Comment by ben-edna** [comment]
+1, would like this, but maybe only for specified tasks:

`IAR: Create Build Task` 

This follows same selection logic as currently (first ewp and then configuration) and will generate a build task.

**Comment by pluyckx** [comment]
All configuration parameters are now exposed using the VSCode settings framework. It is thus now possible to create the build tasks by hand. I will add `task definitions` instead of the command mentioned above as it seems this is a more standard way in vsc.

Reference: [https://code.visualstudio.com/api/references/contribution-points#contributes.taskDefinitions](https://code.visualstudio.com/api/references/contribution-points#contributes.taskDefinitions).

**Comment by pluyckx** [comment]
In the readme you can find a copy/paste ready task to build the selected IAR project, see revision d48d435b3a09cbe6ec5647fb59a42cfdc185e9c4. For the template I will create a new issue.
